version: '3.5'
services:
  web:
    build: .
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app
  redis:
    image: 'redis:alpine'
    command: ['redis-server', '--appendonly', 'yes']
